custom_data:
    mapping:
        file_format: 'tsv'
        section_name: 'Contamination statistics'
        description: "Mapped and unmapped reads (or contigs) for the mapping result against the contamination. Short and sweet: mapped = contamination."
        anchor: 'contamination'
        plot_type: 'bargraph'
        pconfig:
            id: 'Contamination'
            title: 'Contamination statistics'

sp:
    quast:
        fn: '*_report.tsv'
    mapping:
        fn: '*_stats.tsv'

nanostat:
  max_filesize: 4096
  contents: >
    Number, percentage and megabases of reads above quality cutoffs